export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_ALL_EVENTS = 'LOAD_ALL_EVENTS';
export const LOAD_VOTED_EVENT = 'LOAD_VOTED_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
